stream:
  kafka:
    binder:
      auto-add-partitions: true
  bindings:
    input:
      destination: creation-book
      group: group
      binder: kafka
    output:
      destination: check-book
      group: group
      binder: kafka
