spring:
  application:
    name: eureka-client
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    enabled: true
    eureka-service-url-poll-interval-seconds: 35
  instance:
    preferIpAddress: true
