spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        input:
          destination: check-book
          group: group
          binder: kafka